app = "backend-lively-violet-8389"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "1994"
  DB_DIR = "/data"
  STORAGE_ROOT = "/data"
  AUTO_INIT_DB = "0"
  FLASK_ENV = "production"

[[mounts]]
  source = "school_data"
  destination = "/data"

[http_service]
  internal_port = 1994
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1