"""initial

Revision ID: a2a14dc15f61
Revises: 
Create Date: 2026-01-24 02:42:49.873335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a14dc15f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('academic_year', sa.String(length=50), nullable=True),
    sa.Column('theme_color', sa.String(length=30), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_slug'), ['slug'], unique=True)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('stored_name', sa.String(length=300), nullable=False),
    sa.Column('uploader', sa.String(length=80), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_school_id'), ['school_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_school_id'), ['school_id'], unique=False)

    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('filetype', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploader', sa.String(length=120), nullable=True),
    sa.Column('upload_date', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('visibility', sa.String(length=30), nullable=True),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_school_id'), ['school_id'], unique=False)

    op.create_table('school_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('logo_filename', sa.String(length=200), nullable=True),
    sa.Column('principal_name', sa.String(length=120), nullable=True),
    sa.Column('principal_signature_filename', sa.String(length=200), nullable=True),
    sa.Column('teacher_signature_filename', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_settings_school_id'), ['school_id'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_contact', sa.String(length=120), nullable=True),
    sa.Column('home_address', sa.String(length=256), nullable=True),
    sa.Column('emergency_contact', sa.String(length=120), nullable=True),
    sa.Column('photo_filename', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_school_id'), ['school_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('assignee_type', sa.String(length=20), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignee_type'), ['assignee_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_school_id'), ['school_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('attachments_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_pinned'), ['pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_school_id'), ['school_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_school_id'), ['school_id'], unique=False)

    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('cont_ass_score', sa.Integer(), nullable=False),
    sa.Column('exam_score', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_school_id'), ['school_id'], unique=False)

    op.create_table('tuition_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('payment_plan', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tuition_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tuition_info_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tuition_info_student_id'), ['student_id'], unique=False)

    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('tuition_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['tuition_id'], ['tuition_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_history_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_history_tuition_id'), ['tuition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_history_tuition_id'))
        batch_op.drop_index(batch_op.f('ix_payment_history_school_id'))

    op.drop_table('payment_history')
    with op.batch_alter_table('tuition_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tuition_info_student_id'))
        batch_op.drop_index(batch_op.f('ix_tuition_info_school_id'))

    op.drop_table('tuition_info')
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_school_id'))

    op.drop_table('score')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_school_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))

    op.drop_table('attendance')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_school_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_pinned'))
        batch_op.drop_index(batch_op.f('ix_announcement_created_at'))
        batch_op.drop_index(batch_op.f('ix_announcement_audience'))

    op.drop_table('announcement')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_school_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_school_id'))
        batch_op.drop_index(batch_op.f('ix_task_due_date'))
        batch_op.drop_index(batch_op.f('ix_task_audience'))
        batch_op.drop_index(batch_op.f('ix_task_assignee_type'))
        batch_op.drop_index(batch_op.f('ix_task_assignee_id'))

    op.drop_table('task')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_school_id'))

    op.drop_table('student')
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_settings_school_id'))

    op.drop_table('school_settings')
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_school_id'))

    op.drop_table('resource')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_school_id'))
        batch_op.drop_index(batch_op.f('ix_event_date'))
        batch_op.drop_index(batch_op.f('ix_event_audience'))

    op.drop_table('event')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_school_id'))

    op.drop_table('document')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_slug'))

    op.drop_table('school')
    # ### end Alembic commands ###
